#!/bin/bash

# Script to cross-tag CBS builds
#
# example:
#       cross_tag build_name src_release dst_release
#

if [ $# -ne 3 ]; then
    echo "ERROR: syntax error."
    echo "     usage: cross_tag build_name src_release dst_release"
    echo "Exemple:"
    echo "            cross_tag python-oslo-db zed antelope"
    exit 1
fi

build_name=$1
src_release=$2
dst_release=$3


if ! hash cbs 2>/dev/null
then
    echo "'cbs' was not found in PATH"
	exit 1
fi

cbs_tags=$(cbs list-tags 2>/dev/null | grep cloud9s-openstack)
rels=( $src_release $dst_release )
for rel in "${rels[@]}"
do
    echo "$cbs_tags" | grep cloud9s-openstack-$rel-release >/dev/null 2>&1
    if [[ ! $? -eq 0 ]]; then
        echo "Error: $rel doesn't seem to be a known release"
        echo "       the tag cloud9s-openstack-$rel-release does not exist in CBS"
        exit 1
    fi
done

if ! hash rdopkg 2>/dev/null
then
    echo "'rdopkg' was not found in PATH"
    exit 1
fi
pkg_info=$(rdopkg findpkg $1)
src_build=$(echo "$pkg_info" | grep -e "cloud9s-openstack-$src_release-release" | awk '{print $2}')
echo $src_build | grep "^$build_name" >/dev/null 2>&1
if [[ ! $? -eq 0 ]]; then
	echo "Error when finding build in SRC tag"
	exit 1
fi

cbs list-tagged cloud9s-openstack-$dst_release-candidate | grep $src_build >/dev/null 2>&1
if [[ $? -eq 0 ]]; then
	echo "The build '$src_build' is already in cbs tag 'cloud9s-openstack-$dst_release-candidate'"
	exit 0
fi

echo "The commands below will be run:"
CMD_1="cbs add-pkg cloud9s-openstack-$dst_release-candidate --owner rdobuilder $build_name"
CMD_2="cbs tag-build cloud9s-openstack-$dst_release-candidate $src_build"
echo $CMD_1
echo $CMD_2

read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo $CMD_1
    $CMD_1
    echo $CMD_2
    $CMD_2
fi
